# Generated by Django 4.2 on 2023-05-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="pk_location", table="pk_location",),
    ]
